version: 2
jobs:
  build:
    docker:
      - image: openwrt-x86-generic-rootfsi:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Get Interactive prompt
          command: /bin/ash      
